name: "sonar_cloud_scan_github_actions"

on:
  push:
    branches:
      - main

jobs:
  DemoSonarCloudScan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=zicorociz
            -Dsonar.projectKey=zicorociz_DevopsProjectKelompok9
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.java.binaries=target/classes
